# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-07-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automaker', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('color', models.CharField(db_index=True, max_length=30)),
                ('mileage', models.IntegerField()),
                ('motor_potency', models.DecimalField(decimal_places=1, max_digits=6)),
                ('type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('yard.vehicle',),
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('yard.vehicle',),
        ),
    ]
